### ISSUE TITLE
Data corruption in actor/service invocation under high rps

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#1833]
## Expected Behavior

Correct serialization (99.9% of the time) on the HTTP endpoints for actors

## Actual Behavior

When running a Proxy call for the Actor implementation, it randomly fails and spits out a weird JSON string, as if something happened on the protocol transport. Below you can find 2 different occurrences:

**Occurrence dapr/python-sdk#1:**

```bash
# /home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py (line 71)
b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'

# /home/xanrin/dapr-python-sdk/dapr/serializers/json.py (line 49)
b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'

# What I expect:
b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]'
```

**Occurrence dapr/python-sdk#2:**

```bash
# /home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py (line 71)
b'[[0.02180521361883352,0.9327880131478761,-0.04958054991416051,-1.4610110113961423],1.0,false,{}]]'

# /home/xanrin/dapr-python-sdk/dapr/serializers/json.py (line 49)
b'[[0.02180521361883352,0.9327880131478761,-0.04958054991416051,-1.4610110113961423],1.0,false,{}]]'

# What I expect (there is a ] too much):
b'[[0.02180521361883352,0.9327880131478761,-0.04958054991416051,-1.4610110113961423],1.0,false,{}]'
```

## Stacktrace

```bash
== APP == Process ForkServerProcess-4:
== APP == Traceback (most recent call last):
== APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
== APP ==     self.run()
== APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
== APP ==     self._target(*self._args, **self._kwargs)
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 18, in _worker
== APP ==     observation, reward, done, info = env.step(data)
== APP ==   File "/mnt/e/Projects/roadwork-rl/src/Lib/python/roadwork/roadwork/client/client_dapr.py", line 91, in step
== APP ==     obs, reward, done, info = asyncio.get_event_loop().run_until_complete(self.proxy.SimStep({ 'action': action }))
== APP ==   File "/usr/local/lib/python3.7/dist-packages/nest_asyncio.py", line 59, in run_until_complete
== APP ==     return f.result()
== APP ==   File "/usr/lib/python3.7/asyncio/futures.py", line 181, in result
== APP ==     raise self._exception
== APP ==   File "/usr/lib/python3.7/asyncio/tasks.py", line 249, in __step
== APP ==     result = coro.send(None)
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py", line 71, in __call__
== APP ==     return self._message_serializer.deserialize(rtnval, self._attr_call_type['return_types'])
== APP == Actor sending: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP == Decoding: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/serializers/json.py", line 49, in deserialize
== APP == Actor sending: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP == Decoding: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP ==     obj = json.loads(data, cls=DaprJSONDecoder)
== APP ==   File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
== APP ==     return cls(**kw).decode(s)
== APP ==   File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
== APP ==     raise JSONDecodeError("Extra data", s, end)
== APP == json.decoder.JSONDecodeError: Extra data: line 1 column 96 (char 95)
```

## Steps to Reproduce the Problem

This happens when running an application that is utilizing a ThreadPool and running > 1000 reqs / sec (estimated)

**Comment by youngbupark** [comment]
@XavierGeerinck I transferred this to dapr/dapr because this is the runtime bug

**Comment by yaron2** [comment]
Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.

**Comment by youngbupark** [comment]
> Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.

Ok make sense. @XavierGeerinck i will provide the way to use the fix.

@yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..

**Comment by yaron2** [comment]
> > Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.
> 
> Ok make sense. @XavierGeerinck i will provide the way to use the fix.
> 
> @yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..

The perf test doesn't include actors. That's part of 0.10 work.

**Comment by youngbupark** [comment]
> > > Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.
> > 
> > 
> > Ok make sense. @XavierGeerinck i will provide the way to use the fix.
> > @yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..
> 
> The perf test doesn't include actors. That's part of 0.10 work.

The bug is in app channel so the same issue happens in service invocation under high load scenario (1000+ rps)

**Comment by amanbha** [comment]
> > > > Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.
> > > 
> > > 
> > > Ok make sense. @XavierGeerinck i will provide the way to use the fix.
> > > @yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..
> > 
> > 
> > The perf test doesn't include actors. That's part of 0.10 work.
> 
> The bug is in app channel so the same issue happens in service invocation under high load scenario (1000+ rps)

Can perf tests perform deserialization of response and ensure it succeeds.

**Comment by yaron2** [comment]
> > > > > Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.
> > > > 
> > > > 
> > > > Ok make sense. @XavierGeerinck i will provide the way to use the fix.
> > > > @yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..
> > > 
> > > 
> > > The perf test doesn't include actors. That's part of 0.10 work.
> > 
> > 
> > The bug is in app channel so the same issue happens in service invocation under high load scenario (1000+ rps)
> 
> Can perf tests perform deserialization of response and ensure it succeeds.

No, they can only verify status codes of the response.

**Comment by amanbha** [comment]
> > > > > > Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.
> > > > > 
> > > > > 
> > > > > Ok make sense. @XavierGeerinck i will provide the way to use the fix.
> > > > > @yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..
> > > > 
> > > > 
> > > > The perf test doesn't include actors. That's part of 0.10 work.
> > > 
> > > 
> > > The bug is in app channel so the same issue happens in service invocation under high load scenario (1000+ rps)
> > 
> > 
> > Can perf tests perform deserialization of response and ensure it succeeds.
> 
> No, they can only verify status codes of the response.

Should, they should test correctness too? We can add a variation to the tests which can be run as a scale test.

**Comment by yaron2** [comment]
> > > > > > > Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.
> > > > > > 
> > > > > > 
> > > > > > Ok make sense. @XavierGeerinck i will provide the way to use the fix.
> > > > > > @yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..
> > > > > 
> > > > > 
> > > > > The perf test doesn't include actors. That's part of 0.10 work.
> > > > 
> > > > 
> > > > The bug is in app channel so the same issue happens in service invocation under high load scenario (1000+ rps)
> > > 
> > > 
> > > Can perf tests perform deserialization of response and ensure it succeeds.
> > 
> > 
> > No, they can only verify status codes of the response.
> 
> Should, they should test correctness too? We can add a variation to the tests which can be run as a scale test.

I think correctness should not be under the umbrella of performance tests. For example, based on the research I made in performance tests it's highly advisable that the app you are testing never returns a payload back unless you're doing something explicit with the data, instead having the direction go one way to the app.

**Comment by amanbha** [comment]
> > > > > > > > Good we found it, but this does not need a 0.9.1 release and is not under the definition of P0.
> > > > > > > 
> > > > > > > 
> > > > > > > Ok make sense. @XavierGeerinck i will provide the way to use the fix.
> > > > > > > @yaron2 btw, are we validating response for each call in invocation perf test ? Then this would have to be discoverable..
> > > > > > 
> > > > > > 
> > > > > > The perf test doesn't include actors. That's part of 0.10 work.
> > > > > 
> > > > > 
> > > > > The bug is in app channel so the same issue happens in service invocation under high load scenario (1000+ rps)
> > > > 
> > > > 
> > > > Can perf tests perform deserialization of response and ensure it succeeds.
> > > 
> > > 
> > > No, they can only verify status codes of the response.
> > 
> > 
> > Should, they should test correctness too? We can add a variation to the tests which can be run as a scale test.
> 
> I think correctness should not be under the umbrella of performance tests. For example, based on the research I made in performance tests it's highly advisable that the app you are testing never returns a payload back unless you're doing something explicit with the data, instead having the direction go one way to the app.

I understand, how do you propose to uncover these scenarios? perhaps run a variation which does just scale testing without doing perf measurement?

**Comment by yaron2** [comment]
Yes, it probably means a different/new kind of test.

**Comment by youngbupark** [comment]
Interesting. If we check only status code in perf test, how can we convince users to trust our result? Perf test is valid only when functionality is correctly working with the certain condition.

**Comment by yaron2** [comment]
> Interesting. If we check only status code in perf test, how can we convince users to trust our result? Perf test is valid only when functionality is correctly working with the certain condition.

That's not correct, because you are not taking into consideration the goal of our perf test.

The purpose of the current perf test (service invocation) is to report the added latency of the call to the Dapr sidecar. That has nothing to do with the data returned. That is also why the test app does not return a data payload, because it is not part of the test. It just returns a status code to signal that the app has received the call and responded back.

**Comment by yaron2** [comment]
If we create a perf test that has an explicit goal of reporting that the data returned from an app is serialized correctly under a given load, then that would be correct, but in that case as I mentioned above, it's a new test that has a new goal to report.

**Comment by amanbha** [comment]
As I understand, the scenario can be covered by just running other variation of the same perf test which also does validation of the response(could be based on some flag which controls this behavior). If the response is incorrect fail the test.

**Comment by yaron2** [comment]
Yep.

**Comment by youngbupark** [comment]
@XavierGeerinck we merged the fix. You can use this edge version of dapr.

Selfhost mode:
1. dapr uninstall --all
2. dapr init
3. download your edge version of daprd binary from https://github.com/dapr/dapr/actions/runs/180628900
4. replace daprd with edge version 

Kubernetes with helm:
```
helm install helm dapr/dapr --namespace=dapr-system --set-string global.tag=edge
```

**Comment by XavierGeerinck** [comment]
Awesome, thanks! It worked!! :) I ran 8 processes @ ~42 req / s resulting in 100k steps in 294s without a crash!

![image](https://user-images.githubusercontent.com/591282/88374796-b1ced000-cd9a-11ea-9a7a-5b23e75632ca.png)

**Comment by XavierGeerinck** [comment]
Hi There! 

Sadly enough we have to re-open this as the bug is still present 😥 this is the stacktrace we got while testing it during the hackathon (I confirmed that it's the edge version and same binary as I had when it was working...)

```bash
== APP == /usr/local/lib/python3.7/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
 == APP ==   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
 == APP == Process ForkServerProcess-2:
 == APP == Traceback (most recent call last):
 == APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
 == APP ==     self.run()
 == APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
 == APP ==     self._target(*self._args, **self._kwargs)
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 18, in _worker
 == APP ==     observation, reward, done, info = env.step(data)
 == APP ==   File "/home/chipate/roadwork-rl/src/Lib/python/roadwork/roadwork/client/client_dapr.py", line 124, in step
 == APP ==     obs, reward, done, info = self._step(action)
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 139, in __call__
 == APP ==     return call_result.result()
 == APP ==   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
 == APP ==     return self.__get_result()
 == APP ==   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
 == APP ==     raise self._exception
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 204, in main_wrap
 == APP ==     result = await self.awaitable(*args, **kwargs)
 == APP ==   File "/home/chipate/roadwork-rl/src/Lib/python/roadwork/roadwork/client/client_dapr.py", line 60, in _step
 == APP ==     obs, reward, done, info = await self.proxy.SimStep({ 'action': action })
 == APP ==   File "/home/chipate/dapr-python-sdk/dapr/actor/client/proxy.py", line 69, in __call__
 == APP ==     rtnval = await self._proxy.invoke(self._attr_call_type['actor_method'], bytes_data)
 == APP ==   File "/home/chipate/dapr-python-sdk/dapr/actor/client/proxy.py", line 151, in invoke
 == APP ==     self._actor_type, str(self._actor_id), method, raw_body)
 == APP ==   File "/home/chipate/dapr-python-sdk/dapr/clients/http/dapr_actor_http_client.py", line 43, in invoke_method
 == APP ==     return await self._send_bytes(method='POST', url=url, data=data)
 == APP ==   File "/home/chipate/dapr-python-sdk/dapr/clients/http/dapr_actor_http_client.py", line 144, in _send_bytes
 == APP ==     raise (await self.convert_to_error(r))
 == APP == dapr.clients.exceptions.DaprInternalError: ('rpc error: code = Unknown desc = error from actor service: {"errorCode":"UNKNOWN","message":"RuntimeError(\'Task <Task pending coro=<ActorRuntime.dispatch() running at /home/chipate/dapr-python-sdk/dapr/actor/runtime/runtime.py:94> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:157]> got Future <Future pending> attached to a different loop\')"}\n', 'ERR_ACTOR_INVOKE_METHOD')
 == APP == Traceback (most recent call last):
 == APP ==   File "./src/Experiments/baselines/cartpole/train.py", line 27, in <module>
 == APP ==     model.learn(total_timesteps=100000)
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/ppo2/ppo2.py", line 336, in learn
 == APP ==     rollout = self.runner.run(callback)
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/runners.py", line 48, in run
 == APP ==     return self._run()
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/ppo2/ppo2.py", line 482, in _run
 == APP ==     self.obs[:], rewards, self.dones, infos = self.env.step(clipped_actions)
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/base_vec_env.py", line 150, in step
 == APP ==     return self.step_wait()
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 107, in step_wait
 == APP ==     results = [remote.recv() for remote in self.remotes]
 == APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 107, in <listcomp>
 == APP ==     results = [remote.recv() for remote in self.remotes]
 == APP ==   File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
 == APP ==     buf = self._recv_bytes()
 == APP ==   File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
 == APP ==     buf = self._recv(4)
 == APP ==   File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
 == APP ==     raise EOFError
 == APP == EOFError
```

**Comment by yaron2** [comment]
Actually this looks like a different issue.

**Comment by youngbupark** [comment]
> Actually this looks like a different issue.

This is an different issue, I wonder if actor service on flask cannot handle the request at high rps. scaling out actor service would resolve this problem.

**Comment by yaron2** [comment]
> > Actually this looks like a different issue.
> 
> This is an different issue, I wonder if actor service on flask cannot handle the request at high rps. scaling out actor service would resolve this problem.

This makes sense.

**Comment by yaron2** [comment]
@XavierGeerinck the details should be here:

```
dapr.clients.exceptions.DaprInternalError: ('rpc error: code = Unknown desc = error from actor service: {"errorCode":"UNKNOWN","message":"RuntimeError(\'Task <Task pending coro=<ActorRuntime.dispatch() running at /home/chipate/dapr-python-sdk/dapr/actor/runtime/runtime.py:94> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:157]> got Future <Future pending> attached to a different loop\')"}\n', 'ERR_ACTOR_INVOKE_METHOD')
 == APP == Traceback (most recent call last):
```

There should be a more detailed error message, something included with `ERR_ACTOR_INVOKE_METHOD`.

**Comment by youngbupark** [comment]
> @XavierGeerinck the details should be here:
> 
> ```
> dapr.clients.exceptions.DaprInternalError: ('rpc error: code = Unknown desc = error from actor service: {"errorCode":"UNKNOWN","message":"RuntimeError(\'Task <Task pending coro=<ActorRuntime.dispatch() running at /home/chipate/dapr-python-sdk/dapr/actor/runtime/runtime.py:94> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:157]> got Future <Future pending> attached to a different loop\')"}\n', 'ERR_ACTOR_INVOKE_METHOD')
>  == APP == Traceback (most recent call last):
> ```
> 
> There should be a more detailed error message, something included with `ERR_ACTOR_INVOKE_METHOD`.

@XavierGeerinck as we spoke, let's add simple retry with try-catch using for-loop. in catch block, please print out detail error message.

**Comment by XavierGeerinck** [comment]
![image](https://user-images.githubusercontent.com/591282/88585990-19fc0b00-d054-11ea-9982-55a3ea10277c.png)

This is the stacktrace with try except :)

**Comment by youngbupark** [comment]
no this is different one from above. can you check runtime version?
dapr --version

runtime version must be edge
