### ISSUE TITLE
dapr-api-token passed back to the application 'as-is' when proxying

### ISSUE THREAD

**Issue by vermillionsword** [dapr/dapr#7344]
## In what area(s)?

/area runtime

## What version of Dapr?

1.11.2
1.12.2

## Expected Behavior
I expect that when I proxy a service invocation through dapr using gRPC that the dapr-api-token header is updated to use the app-token-secret instead of the api-token-secret that I sent with my request.

## Actual Behavior
I am instead receiving the same value I sent on the dapr-api-token header to the sidecar in the receiving service.

## Steps to Reproduce the Problem
Setup:
- Run the latest dapr installation
- Run a plain gRPC service (C# preferably, though I assume this will happen with any proxied call)
- Turn on both `dapr.io/app-token-secret: "app-api-token"` and `dapr.io/api-token-secret: "dapr-api-token"`
- Create secrets as described in the documentation

Steps:
- Make a call to the service through dapr transparently (service proxying)
- Add `dapr-api-token` header to the request using the `dapi-api-token` secret
- Observe the dapr-api-token header, it will not be the `app-api-token` secret, instead it will still be the `dapr-api-token` secret

## Release Note

RELEASE NOTE: **FIX** dapr-api-token header population for proxied calls

**Comment by vermillionsword** [comment]
The issue seems to be around line 138 of https://github.com/dapr/dapr/blob/master/pkg/messaging/grpc_proxy.go

Notice how the outgoing context does not get the `dapr-api-token` appended to it from security.GetAppToken() unlike

https://github.com/dapr/dapr/blob/master/pkg/channel/grpc/grpc_channel.go

**Comment by yaron2** [comment]
> The issue seems to be around line 138 of https://github.com/dapr/dapr/blob/master/pkg/messaging/grpc_proxy.go
> 
> Notice how the outgoing context does not get the `dapr-api-token` appended to it from security.GetAppToken() unlike
> 
> https://github.com/dapr/dapr/blob/master/pkg/channel/grpc/grpc_channel.go

Yes, you've correctly identified where the token needs to be added. Would you be interested in opening a PR for this?

**Comment by vermillionsword** [comment]
@yaron2 sure. I think I can do that.

**Comment by yaron2** [comment]
Great. I've triaged it to 1.13 and we can accept this PR after our code freeze (already in effect) due to the security fix. cc @JoshVanL

**Comment by JoshVanL** [comment]
Fixed in https://github.com/dapr/dapr/pull/7404

**Comment by marcel-tomate** [comment]
I'm still facing this issue on runtime 1.13.4 during local development with multiapp run `dapr run -f .`.
`APP_API_TOKEN` seems to have no effect at all (setting it either on receiver/caller or both). Only receiving the `dapr-api-token` in my grpc handler, if I add the `DAPR_API_TOKEN` environment variable to the caller service - but the value is from `DAPR_API_TOKEN`.

- I don't expect it to be set on my grpc handler at all (since it is the dapr api token, set on the caller service)
- Expect it to be set/overwritten by my specified `APP_API_TOKEN` for this service.

What do I get wrong? @JoshVanL

**Comment by vermillionsword** [comment]
> I'm still facing this issue on runtime 1.13.4 during local development with multiapp run `dapr run -f .`. `APP_API_TOKEN` seems to have no effect at all (setting it either on receiver/caller or both). Only receiving the `dapr-api-token` in my grpc handler, if I add the `DAPR_API_TOKEN` environment variable to the caller service - but the value is from `DAPR_API_TOKEN`.
> 
> * I don't expect it to be set on my grpc handler at all (since it is the dapr api token, set on the caller service)
> * Expect it to be set/overwritten by my specified `APP_API_TOKEN` for this service.
> 
> What do I get wrong? @JoshVanL

I was confused about this too initially. Setting the env var DAPR_API_TOKEN on your services sends the token to dapr for authentication against the secret dapr-api-token. Then the app-api-token secret is sent back to your service and YOU must authenticate the call by hand, which the documentation recommends using an environment variable called APP_API_TOKEN for, but could be any env var.

**Comment by marcel-tomate** [comment]
@vermillionsword Thanks for your response, I'm still not sure I fully understand this.

> **Then the app-api-token secret is sent back** 

The DAPR_API_TOKEN? Which is also still called dapr-api-token in the grpc metadata?

> **YOU must authenticate the call by hand**

I already understand this by now, but it also took me some time...

> **using an environment variable called APP_API_TOKEN for, but could be any env var.**

I think I'm starting to understand, but just to be sure, why not use the same DAPR_API_TOKEN again?
